# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45f9e04e1e80f9e7dcf019646fe5434e31285fe18792592934c00d1eec8b09948fb6663f004798aefc8e5468735a43e34dfc2c1e3b197f972a6546255ec1c4dd

test:
  secret_key_base: c93ee5de42ac91978a9d81452e726b0e5d1fb2d368402d7e16d0011c6e68fc7890019e14211626c6d4cb79b795d93f7e0461f5b80ef56ebe67db0b10d9aec97a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
